import React, { useState } from "react";
import styled from "styled-components";

import Footer from "../component/Seongju_Footer";
import Grid from "../component/Seongju_Grid";
import Header from "../component/Seongju_Header";
import Main from "../component/Seongju_Main";
import SignUp from "../component/Seongju_signup";

/*
 * Replace the elements below with your own.
 *
 * Note: The corresponding styles are in the ./index.styled-components file.
 */
const WelcomePageMain = (): JSX.Element | null => {
    const [grid, setgrid] = useState(false);

    /**
     * Redirects to another page generated by replacing the path in the original URL
     * with the given path.
     *
     * @param {(string)} pathname - The path to navigate to.
     * @returns {Function}
     */
    return (
        <Welcome>
            <Header />
            <Main grid={grid} setgrid={setgrid} />
            <Grid grid={grid} />
            <Footer />
            {/* <SignUp /> */}
        </Welcome>
    );
};

// 제일 바깥쪽 레이아웃 잡기
const Welcome = styled.div`
    width: 100%;
`;

export default WelcomePageMain;
