import React, { useState } from "react";
import styled from "styled-components";

import Header from "../component/nxdf_Header";
import Main from "../component/nxdf_Main";

/*
 * Replace the elements below with your own.
 *
 * Note: The corresponding styles are in the ./index.styled-components file.
 */
const ProfilePage = (props) => {
    const [grid, setgrid] = useState(false);

    /**
     * Redirects to another page generated by replacing the path in the original URL
     * with the given path.
     *
     * @param {(string)} pathname - The path to navigate to.
     * @returns {Function}
     */
    return (
        <Welcome>
            <Header />
            <Div>
                <h1>Utility Setting</h1>
                <WalletSec>
                    <Wel>
                        <span>polygon</span>
                        <span>:</span>
                        <span>0xa238B6e0e585A9df7F3B97d3611Cd548D58d0631</span>
                    </Wel>
                    <span>
                        Your MetaAxel PFP will be registered by staking program.
                        The smart contract lets you not to transfer while you
                        use NXDF Meet service. However, the PFP holder can
                        unstake whenever he/she wants not to use this service in
                        this page.
                    </span>
                </WalletSec>
                <ProfileSetting>
                    <MyNFTs>
                        <h1>My NFTs</h1>
                        <MyNFTsSec>
                            <MyNFTContent>
                                <img height={"50%"} width={"10%"} />
                                <MynftsMiniDesc>
                                    <span>Burnt Pink Squad Origin #1120</span>
                                    <span>Type : Player Item</span>
                                </MynftsMiniDesc>
                            </MyNFTContent>
                        </MyNFTsSec>
                    </MyNFTs>
                    <MyStake>
                        <StakeBtnSec />
                        <UnStakeBtnSec />
                    </MyStake>
                    <MyProfile>
                        <h1>My Profile Utility</h1>
                        <MyNFTsSec>
                            <SeletctNFT>
                                <SeletctNFTImg height={"50%"} width={"100%"} />
                                <div>
                                    <h4>Burnt Pink Squad Origin #1120</h4>
                                    <span>Type : Player Item</span>
                                </div>
                                <div>
                                    <div>
                                        <span>Character</span>
                                        <span>Rosie Blue Sapphire</span>
                                    </div>
                                </div>
                            </SeletctNFT>
                        </MyNFTsSec>
                    </MyProfile>
                </ProfileSetting>
            </Div>
        </Welcome>
    );
};

// 제일 바깥쪽 레이아웃 잡기
const Welcome = styled.div`
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
`;

const Wel = styled.div`
    padding: 1rem 0px;
`;

const Div = styled.div`
    width: 50%;
    margin-top: 5rem;
    display: flex;
    flex-direction: column;
    color: #797979;

    h1 {
        text-align: center;
    }
`;

const WalletSec = styled.div`
    margin: 2rem 0px;
    display: flex;
    flex-direction: column;
`;

const StakeBtnSec = styled.div`
    padding: 1rem;
    min-height: 60px;
    background-image: url("/images/stake_icon.svg");
    background-repeat: no-repeat;
    background-size: contain;
    background-position: center;
`;
const UnStakeBtnSec = styled(StakeBtnSec)`
    background-image: url("/images/unstake_icon.svg");
`;

const ProfileSetting = styled.div`
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
`;

const MyNFTs = styled.div`
    width: 40%;
`;

const MyNFTsSec = styled.div`
    width: 100%;
    min-height: 400px;
    margin-top: 1rem;
    border-radius: 1rem;
    padding: 1rem 0px;
    background-color: #fafdff;
`;

const MyNFTContent = styled.div`
    display: flex;
    align-items: center;
    justify-content: center;
`;
const MyStake = styled.div`
    width: 20%;
`;

const MynftsMiniDesc = styled.div`
    display: flex;
`;

const SeletctNFT = styled.div``;
const SeletctNFTImg = styled.img`
    background-color: black;
    min-height: 200px;
`;
const MyProfile = styled.div`
    width: 40%;
`;

export default ProfilePage;
